---
title: "MSigDb"
output: html_document
---

```{r setup, include=FALSE}
library(clusterProfiler)
library(magrittr)
library(dplyr)
library(clusterProfiler)
library(ggplot2)
library(tidyr)
library(tidytext)

knitr::opts_chunk$set(echo = FALSE)
```


```{r}

data_file <- readRDS("../data/data14Features.rds")
analysis_data <-metadata(data_file)$limma[,"Sirt_vs_Mock",]%>%
  as.data.frame()%>%
  dplyr::select(effect,p)%>%
  cbind(.,ENTREZ_ID = rowData(data_file)$ENTREZID)

analysis_data$ENTREZ_ID <- analysis_data$ENTREZ_ID %>%
  stringr::str_split(.,";",simplify=TRUE)%>%
  .[,1]

geneList <- analysis_data %>% dplyr::filter(ENTREZ_ID != "" & effect != "")%>% 
  dplyr::select(ENTREZ_ID,effect,p)

#define groups 1-3
geneList <- mutate(geneList, grp_id = ifelse(p <= 0.05 & effect <= 0, 1,
                                             ifelse(p <= 0.05 & effect >= 0, 2, 3)))
```

```{r}
#Extract data from MSigDb Analysis and perform ORA
msigdbr_data <- msigdbr::msigdbr(species = "Mus musculus")%>%
  dplyr::select(gs_name, entrez_gene, gs_cat)

cat_vector <- c("H","C2","C5")
no_of_grps <- geneList$grp_id %>% unique() %>% .[!is.na(.)]

musculus_cat_data <- cat_vector %>% lapply(.,function (x) {
  
  catgry_dataset <- msigdbr_data %>% dplyr::filter(gs_cat == x)
  
  ora_list <- no_of_grps %>% lapply(., function(y) {
    gene_oi<- geneList %>% dplyr::filter(grp_id == y & ENTREZ_ID != "")
    enriched_result <- enricher(gene = gene_oi$ENTREZ_ID, TERM2GENE = catgry_dataset,universe = geneList$ENTREZ_ID)
    enriched_result@result %>%
      dplyr::mutate(p_log = -1*log(pvalue, 10))%>%
      dplyr::filter(p_log > 1.3) -> enrchresult_plog
    enrchresult_plog %>% mutate(msig_cat = x , p_cat = y)
  })
  ora_list %>% do.call(rbind, .)
})

# Plotting ----------------------------------------------------------------
musculus_cat_df <- musculus_cat_data %>% do.call(rbind, .) 
```


```{r}

# df ordered by p_log
plot <- musculus_cat_df %>% dplyr::filter(msig_cat == "H") %>%
  arrange(p_cat, p_log) %>%
  mutate(order = row_number())
 
plot %>%
  ggplot(aes(x=order,y= p_log)) +
  geom_bar(stat = "identity", fill="salmon2", alpha=0.8)+
  facet_wrap(~p_cat)+
  theme_bw()+
  # Add Description to x axis
  scale_x_continuous(
    breaks = plot$order,labels = plot$Description, c(0,0)
  )+
  coord_flip()

```

```{r}

# df ordered by p_log
plot <- musculus_cat_df %>% dplyr::filter(msig_cat == "C5") %>%
  arrange(p_cat, p_log) %>%
  mutate(order = row_number())
 
plot %>%
  ggplot(aes(x=order,y= p_log)) +
  geom_bar(stat = "identity", fill="salmon2", alpha=0.8)+
  facet_wrap(~p_cat)+
  theme_bw()+
  # Add Description to x axis
  scale_x_continuous(
    breaks = plot$order,labels = plot$Description, c(0,0)
  )+
  coord_flip()

```

```{r}

# df ordered by p_log
plot <- musculus_cat_df %>% dplyr::filter(stringr::str_detect(ID, "REACTOME")) %>%
  arrange(p_cat, p_log) %>%
  mutate(order = row_number())
 
plot %>%
  ggplot(aes(x=order,y= p_log)) +
  geom_bar(stat = "identity", fill="salmon2", alpha=0.8)+
  facet_wrap(~p_cat)+
  theme_bw()+
  # Add Description to x axis
  scale_x_continuous(
    breaks = plot$order,labels = plot$Description, c(0,0)
  )+
  coord_flip()

```

```{r}

# df ordered by p_log
plot <- musculus_cat_df %>% dplyr::filter(stringr::str_detect(ID, "BIOCARTA")) %>%
  arrange(p_cat, p_log) %>%
  mutate(order = row_number())
 
plot %>%
  ggplot(aes(x=order,y= p_log)) +
  geom_bar(stat = "identity", fill="salmon2", alpha=0.8)+
  facet_wrap(~p_cat)+
  theme_bw()+
  # Add Description to x axis
  scale_x_continuous(
    breaks = plot$order,labels = plot$Description, c(0,0)
  )+
  coord_flip()

```

```{r}

# df ordered by p_log
plot <- musculus_cat_df %>% dplyr::filter(stringr::str_detect(ID, "KEGG")) %>%
  arrange(p_cat, p_log) %>%
  mutate(order = row_number())
 
plot %>%
  ggplot(aes(x=order,y= p_log)) +
  geom_bar(stat = "identity", fill="salmon2", alpha=0.8)+
  facet_wrap(~p_cat)+
  theme_bw()+
  # Add Description to x axis
  scale_x_continuous(
    breaks = plot$order,labels = plot$Description, c(0,0)
  )+
  coord_flip()

```

```{r}

# df ordered by p_log
plot <- musculus_cat_df %>% 
  dplyr::filter(msig_cat == "C2") %>%
  dplyr::filter(!stringr::str_detect(ID, "REACTOME|KEGG|BIOCARTA|PID"))  %>%
  arrange(p_cat, p_log) %>%
  mutate(order = row_number())
 
plot %>%
  ggplot(aes(x=order,y= p_log)) +
  geom_bar(stat = "identity", fill="salmon2", alpha=0.8)+
  facet_wrap(~p_cat)+
  theme_bw()+
  # Add Description to x axis
  scale_x_continuous(
    breaks = plot$order,labels = plot$Description, c(0,0)
  )+
  coord_flip()

```






