---
title: "clustering_4 - Data _Festure table based"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(clusterProfiler)
library(ggplot2)
library(tidyr)
library(tidytext)
library(magrittr)
library(BiocManager)
library(SummarizedExperiment)
library(mixOmics)
library(remotes)
library(assertive.types)
library(autonomics)
library(pheatmap)
library(ppclust)
library(enrichplot)
library(org.Mm.eg.db)
library(stringr)
library(enrichplot)

knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data_file <- readRDS("../data/data14Features.rds")
#data_file <- readRDS("~/data14Features.rds")
```


```{r}
# data_prep ()function returns an object that has Feautre details + p and effect[@limma]- a DF with 16 columns
data_prep <- function(data_input_file, contrast_def_name){
  data_input_file_result <- data_input_file@metadata$limma[,contrast_def_name,] %>% 
    as.data.frame() %>% 
    dplyr::select(effect,p) %>% 
    tibble::rownames_to_column(var= "feature_id") %>% 
    dplyr::left_join(fdata(data_input_file), ., by = "feature_id")
  #dplyr::filter(ENTREZID != "" & p != "")
  return(data_input_file_result)
}
```

```{r}
add_cluster <- function (data_input_file,
                         cluster_type = NULL,
                         contrast_def_name = NULL,
                         sig_level = 0.05,
                         dclust_sig = 0.05,
                         k = 5,
                         plot = FALSE,
                         ...){
  
  assertive.types::assert_is_any_of(cluster_type, classes = c("NULL", "character"))
  assertive.types::assert_is_any_of(contrast_def_name, classes = c("NULL", "character"))
  sig_level %>% assertive.types::assert_is_a_number()
  k %>% assertive.types::assert_is_a_number() %>%
    assertive.numbers::assert_all_are_whole_numbers() %>%
    assertive.numbers::assert_all_are_greater_than(0)
  
  contrast_def_name <- match.arg(contrast_def_name, names(data_input_file@metadata$contrastdefs), several.ok = FALSE)
  cluster_type <- match.arg(cluster_type, c("pval", "pval_bins", "bins", "dclust", "fuzzy"), several.ok = FALSE)
  
  if (cluster_type == "pval") {
    x <- data_prep(data_input_file, contrast_def_name) %>% 
      dplyr::mutate(clust_pval =  ifelse(p <= sig_level & effect <= 0, 1,ifelse(p <= sig_level & effect >= 0, 2, 3)))
    return (x)
  }
  
  if (cluster_type == "pval_bins"){
    fdata(data_input_file) <- data_prep(data_input_file,contrast_def_name ) %>%
      dplyr::mutate(clust_pbins = ifelse(p <= 0.05 & effect <= 0, 1,
                                         ifelse(p <= 0.22 & p > 0.05 & effect <= 0, 2,
                                                ifelse(p <= 0.5 & p > 0.22 & effect <= 0, 3,
                                                       ifelse(p <= 0.5 & p > 0.22 & effect >= 0, 4,
                                                              ifelse(p <= 0.22 & p > 0.05 & effect >= 0, 5,
                                                                     6))))))
    return(fdata(data_input_file))
  }
  
  if (cluster_type == "bins"){
    fdata(data_input_file) <- data_prep(data_input_file, contrast_def_name) %>%
      dplyr::mutate(clust_bins = cut(p, k, labels = seq(1, k, by=1)))
    return(fdata(data_input_file))
  }
} 

#  if (cluster_type == "dclust") {
#    subgroup_oi <- object@metadata$contrastdefs[contrast] %>% stringr::str_split("-", simplify = TRUE)
#    
#    p_oi <- (object@metadata$limma[, contrast, "p"] <= dclust_sig) %>%
#      replace(is.na(.), FALSE)
#    
#    exprs_vals <- exprs(object)[, object$subgroup %in% subgroup_oi] %>%
#      .[p_oi, ] %>%
#      replace(is.na(.), 0) ### needs better permutation of NAs
#    
#    out <- pheatmap::pheatmap(exprs_vals,
#                              scale = "row",
#                              clustering_distance_rows = "euclidean",
#                              clustering_distance_cols = "euclidean",
#                              clustering_method = "complete", show_rownames = FALSE)
#    
#    fdata(object) <- cutree(out$tree_row, k = k) %>% 
#      as.data.frame() %>% 
#      `colnames<-`(c("clust_dclust")) %>% 
#      tibble::rownames_to_column(var = "feature_id") %>%
#      dplyr::left_join(fdata(object), ., by = "feature_id")
#    
#    if(plot == TRUE) {
#      plot(out$tree_row)
#      abline(h = out$tree_row$height[length(out$tree_row$height)-(k-2)], 
#               col = "red", lty = 2, lwd = 2)
#    }
#    
#  return(object) 
# }

# fuzzy will not be implemented now
# if (cluster_type == "fuzzy") {
#     out <- ppclust::fcm(data, centers=3)
#     ppclust::plotcluster(out, trans=TRUE)
#     return(out)
# }  

```


```{r}
# --------- Annotation Function -- Default should not be Null, change it later----
# -- This function should contain links for species other than mouse

annotate_func <- function(dbtype = NULL, species = NULL)
{
  dbtype <- match.arg(dbtype, c("wiki", "kegg", "go"), several.ok = FALSE)
  species <- match.arg(species, c("mouse", "Homo_sapiens"), several.ok = FALSE)
  
  if (dbtype == "wiki" & species == "mouse")
  {
    wiki <- read.gmt("~/r_projects/mashood_ora/data/wikipathways-20191210-gmt-Mus_musculus.gmt")%>%
      #wiki <- read.gmt("~/GitHub/rep_bioinfo/wikipathways-20191210-gmt-Mus_musculus.gmt")%>%
      tidyr::separate(ont,c("name","version","wpid","org"),"%")
    wiki_result <- wiki %>% dplyr::select(wpid,gene,name)
    return(wiki_result)
  }
  
  # if (dbtype == "kegg" & species == "mouse")
  # {
  #   
  # }
  # 
  # if (dbtype == "go" & species == "mouse")
  # {
  #   
  # }
}
```

```{r warning=TRUE}
# step 1 - call add cluster funcion and save the result - here im working with pval + sirt_vs_mock
over_rep_an_function <- function(data_input_file, cluster_type = NULL, contrast_def_name = NULL, dbtype = NULL, species = "mouse") 
{
  analysis_data <- add_cluster(data_input_file,cluster_type, contrast_def_name ,sig_level = 0.05, dclust_sig = 0.05, k = 5, plot = FALSE)
  #analysis_data$ENTREZ_ID <- analysis_data$ENTREZID %>% stringr::str_split(.,";",simplify=TRUE) %>% .[,1]

# step 2 - Define Gene_Universe
  gene_universe <- analysis_data %>% .[ ,c("ENTREZID")] %>% as.character()
  
  # !! Value in no_of_groups will vary based on the value passed in to add_cluster func-- include it here
  # hardocing $clust_pval will cause errors with othe cluster types
  #no_of_grps <- analysis_data$clust_pval %>% unique() %>% .[!is.na(.)]
  no_of_grps <- analysis_data %>% dplyr::select(starts_with("clust_"))%>% unique() %>% .[!is.na(.)] 
  dbtype <- match.arg(dbtype, c("wiki_enrich","kegg_enrich","go_enrich"), several.ok = FALSE)
  
  # Store clusterid into a diff variable and use if condition..
  cluster_ids <- c("clust_pbins" , "clust_bins", "clust_pval")
  
  if (cluster_type == "pval"){
    analysis_data$clust_pval -> analysis_data$cluster_id
  }
  
  if (cluster_type == "pval_bins"){
    analysis_data$clust_pbins -> analysis_data$cluster_id
  }
  
  if (cluster_type == "bins"){
    analysis_data$clust_bins -> analysis_data$cluster_id
  }
  
  # -----------------------------------------------------------------------------------
  if (dbtype == "kegg_enrich")
  {
    kk_ora_result <- no_of_grps %>% lapply(.,function(x)
    {
      gene_oi <- analysis_data %>% dplyr::filter(cluster_id == x & ENTREZID != "")
      # second option - below code creates a vector of differnt column names that hold cluster ids. 
      # alternate option - is to create  a vector with different cluster_id_names
      
      # colnames(analysis_data) -> colnames_storage
      # colnames_storage[grepl("clust_", colnames_storage)] -> col_name_to_loop
      
      # gene_oi = NULL
      # for (i in cluster_ids) {
      #   gene_oi <- analysis_data %>% dplyr::filter(i == x)
      # }
      kegg_enrichr_result <-enrichKEGG(gene = gene_oi$ENTREZID ,universe = gene_universe, organism = "mmu", pvalueCutoff = 0.05)
      kegg_enrichr_result@result %>% dplyr::mutate(p_log = -1 * log(pvalue, 10)) %>%
        dplyr::filter(p_log > 1.3) -> plot_ora_kegg
      plot_ora_kegg %>% mutate(clust_id = x)
      
    })
    return(kk_ora_result)
  }
  
  # -----------------------------------------------------------------------------------
  if (dbtype == "wiki_enrich")
  {
    wiki_ora_result <- no_of_grps %>% lapply(.,function(x)
    {
      gene_oi <- analysis_data %>% dplyr::filter(cluster_id == x & ENTREZID != "")
      # subset_gene_clusts <- subset(analysis_data, select = grep("clust_", names(analysis_data)))
      # gene_oi <- analysis_data %>% dplyr::filter(subset_gene_clusts == x)
      wiki_enrichr_result <- enricher(gene = gene_oi$ENTREZID, 
                                      universe = gene_universe,
                                      pvalueCutoff = 0.05, 
                                      TERM2GENE = annotate_func(dbtype = "wiki", species = "mouse") %>% dplyr::select(wpid,gene), 
                                      TERM2NAME = annotate_func(dbtype = "wiki",species = "mouse") %>% dplyr::select(wpid,name))
      
      wiki_enrichr_result@result %>% dplyr::mutate(p_log = -1 * log(pvalue, 10)) %>%
        dplyr::filter(p_log > 1.3) -> plot_ora_wiki
      plot_ora_wiki %>% mutate(clust_id = x)
    })
    return(wiki_ora_result)
  }
 # ----------------------------------------------------------------------------------- 
  if (dbtype == "go_enrich")
  {
    go_ora_result <- no_of_grps %>% lapply(.,function(x)
    {
      gene_oi <- analysis_data %>% dplyr::filter(cluster_id == x & ENTREZID != "")
      print(gene_oi)
      go_enrichr_result <- enrichGO(gene = gene_oi$ENTREZID,
                                    universe = gene_universe,
                                    OrgDb = org.Mm.eg.db,
                                    ont = "CC",
                                    pvalueCutoff = 0.05,
                                    pAdjustMethod = "BH",
                                    qvalueCutoff = 0.05,
                                    readable = TRUE)
      go_enrichr_result@result %>% dplyr::mutate(p_log = -1 * log(pvalue, 10)) %>%
        dplyr::filter(p_log > 1.0) -> plot_ora_go 
      plot_ora_go %>% mutate(clust_id = x)
      
    })
    
    return(go_ora_result)
  }   
}

```

```{r}
ora_go <- over_rep_an_function(data_file, contrast_def_name = "Sirt_vs_Mock", cluster_type = "pval_bins", dbtype = "go_enrich") 

ora_go %>% do.call(rbind,.) -> plot_df


```

```{r}
# ------ Function to handle plotting - ADVANCED  -----
# user should be allowed to plot - heatmaps, dot plots or bar plots

plot_ORA_outcome <- function(data_input_file,
                             plot_type = NULL, 
                             cluster_type = NULL, 
                             contrast_def_name = NULL, 
                             dbtype = NULL,
                             dclust_sig = 0.05
                             #contrast = NULL
) 
{
  plot_type <- match.arg(plot_type, c("BarPlot", "DotPlot", "Heatmap", "Heatplot"), several.ok = FALSE)
  contrast_def_name <- match.arg(contrast_def_name, names(data_input_file@metadata$contrastdefs), several.ok = FALSE)
  
  ora_result <- over_rep_an_function(data_input_file, cluster_type, contrast_def_name, dbtype)
  
  plot_df <- ora_result %>% do.call(rbind,.)
  
  plot_2 <- plot_df %>%	arrange(clust_id, p_log) %>% mutate(order = row_number())
  
  if (plot_type == "BarPlot")
  {
    plot_BarPlot <- plot_2 %>% 
      ggplot(aes(x=order,y= p_log)) +
      geom_bar(stat = "identity", fill="aquamarine3", alpha=0.8)+
      facet_wrap(~ clust_id) +
      coord_flip() +
      scale_x_continuous(breaks = plot_2$order,labels = plot_2$Description, position = "bottom") + 
      theme_bw()
    return(plot_BarPlot)
  }
  
  if (plot_type == "DotPlot")
  {
    plot_DotPlot <- plot_2 %>%
      ggplot(aes(x = Description, y = p_log)) + 
      geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1.3, stackratio = 1.5, fill = "red" ) +
      facet_wrap(~ clust_id) +
      coord_flip() +
      #(breaks = plot$order,labels = plot$Description) + 
      theme_bw()
    
    return(plot_DotPlot)
    
  }
  
 if (plot_type == "Heatplot") {
   heatplot(ora_result, showCategory = 30, foldChange = NULL)
   }
 
 # if (type == "Heatmap")
 #   {
 #   plot <- object %>% arrange(Group_ID, p_log)
 #   plot_Heatmap <- pheatmap::pheatmap(add_matrix, scale = "row", clustering_distance_rows = "euclidean",clustering_distance_cols = "euclidean",clustering_method = "complete",show_rownames = FALSE)
 #   
 #  # get a matrix and draw a heatmap
 #  return(plot_Heatmap)
 #   
  if (plot_type == "Heatmap") 
  {
    subgroup_oi <- data_input_file@metadata$contrastdefs[contrast_def_name] %>% stringr::str_split("-", simplify = TRUE)
    
    p_oi <- (data_input_file@metadata$limma[, contrast_def_name, "p"] <= dclust_sig) %>%
      replace(is.na(.), FALSE)
    
    exprs_vals <- exprs(data_input_file)[, data_input_file$subgroup %in% subgroup_oi] %>%
      .[p_oi, ] %>%
      replace(is.na(.), 0) ### needs better permutation of NAs
    
    # pheatmaps
    out <- pheatmap::pheatmap(exprs_vals,
                              scale = "row",
                              clustering_distance_rows = "euclidean",
                              clustering_distance_cols = "euclidean",
                              clustering_method = "complete", show_rownames = FALSE)
    
    # Adds clusterid to fdata of the main file
    fdata(data_input_file) <- cutree(out$tree_row, k = k) %>% 
      as.data.frame() %>% 
      `colnames<-`(c("clust_dclust")) %>% 
      tibble::rownames_to_column(var = "feature_id") %>%
      dplyr::left_join(fdata(data_input_file), ., by = "feature_id")
    
    # plots dendograms
    if(plot == TRUE) {
      plot(out$tree_row)
      abline(h = out$tree_row$height[length(out$tree_row$height)-(k-2)], 
             col = "red", lty = 2, lwd = 2)
    }
    
    # return(object) 
  } 
   
   
   
}


```

```{r}
# TESTING ORA_FUNCTION
# Note only the last if condition is printed - do not define a RETURN. it works fine without a return
over_rep_an_function(data_file, contrast_def_name = "Sirt_vs_Mock", cluster_type = "pval_bins", dbtype = "go_enrich") -> ora_go


over_rep_an_function(data_file, contrast_def_name = "Sirt_vs_Mock", cluster_type = "pval", dbtype = "kegg_enrich") -> ora_kegg

plot_ORA_outcome (data_file, plot_type = "Heatmap", 
                             cluster_type = "pval", 
                             contrast_def_name = "Sirt", 
                             dbtype = "kegg_enrich")


```

```{r}
# funtion to handle the process prior to plotting
# add_cluster () + ora () then the below function
# COMPLETE THIS FUNCTION - instead f doing 27 seperate tests -- try the below

overall_function <- function(data_input_file, type, contrast_def_name, dbtype){
  contrast_list <- c("Sirt_vs_Mock", "Sirt", "Mock")
  group_on_list <- c("pval", "pval_bins", "bins")
  db_list <- c("wiki", "go", "kegg")
  
  for (contrast_i in contrast_list) {
    for (grpon_i in group_on_list) {
      analysis_data <- add_cluster(data_input_file, type, contrast_def_name)
      for (dblist_i in db_list) {
        ora_list <- ora_funct(data_input_file, dbtype)
        
      }
    }
    
  }
}

```



