---
title: "heatmap_enricher"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(clusterProfiler)
library(ggplot2)
library(tidyr)
library(tidytext)
library(magrittr)
library(BiocManager)
library(SummarizedExperiment)
library(mixOmics)
library(remotes)
library(assertive.types)
library(autonomics)
library(pheatmap)
library(ppclust)
library(enrichplot)
library(org.Mm.eg.db)
library(stringr)
library(enrichplot)
```

```{r}
#data_file <- readRDS("../data/data14Features.rds")
data_file <- readRDS("~/data14Features.rds")

```

```{r}
analysis_data <- data_file@metadata$limma[, "Sirt_vs_Mock", ] %>%
  as.data.frame() %>%
  dplyr::select(effect,p) %>%
  cbind(.,ENTREZ_ID = rowData(data_file)$ENTREZID)

analysis_data$ENTREZ_ID <- analysis_data$ENTREZ_ID %>%
  stringr::str_split(.,";",simplify=TRUE) %>%
  .[,1]

geneList <- analysis_data %>% dplyr::filter(ENTREZ_ID != "" & effect != "") %>%   dplyr::select(ENTREZ_ID,effect,p)

#define groups 1-3
geneList <- mutate(geneList, grp_id = ifelse(p <= 0.05 & effect <= 0, 1,
                                                   ifelse(p <= 0.05 & effect >= 0, 2, 3)))

```


```{r}
no_of_grps <- geneList$grp_id %>% unique() %>% .[!is.na(.)]

ora_list <- no_of_grps %>% lapply(., function(x){
  gene_oi <- geneList %>% dplyr::filter(grp_id == x & ENTREZ_ID != "")
  enrichr_result <- enrichKEGG(gene = gene_oi$ENTREZ_ID,universe = geneList$ENTREZ_ID,organism ='mmu',pvalueCutoff = 0.05)
enrichr_result@result %>%
  dplyr::mutate(p_log = -1*log(pvalue, 10))%>%
  dplyr::filter(p_log > 1.3) -> enrchresult_Grp
enrchresult_Grp %>% 
  mutate(grp_id = x)
})

# Bind data frames returned from all groups  and save it as a data frame
# do.call(rbind, .) only accepts lists. hence we convert it into a DF in the next line
ora_list_df <- ora_list %>% do.call(rbind, .)
```

```{r}
# Fetches the Contrast Defs name and splits the text at "-"
# subgroup_oi <- object@metadata$contrastdefs[contrast] %>% stringr::str_split("-", simplify = TRUE)
      
      # Fetches records where P is less than dclust_sig, passed at the begining
      # Returns a logical vector
      # gene of interest 
# p_oi <- (object@metadata$limma[, contrast, "p"] <= dclust_sig) %>%
        # replace(is.na(.), FALSE)
      
      # exprs() returns a matrix that contain experiment data
      # compares <data_file$subgroups> against the <@metadata$contrastdefs>
      # Filter experiment data - display only proteins that have a sig_level > 0.05
      # [%in%] returns a logical vector indicating if there is a match or not for its left operand
      # subsetting based on a certain condition
# exprs_vals <- exprs(object)[, object$subgroup %in% subgroup_oi] %>%
#         .[p_oi, ] %>% replace(is.na(.), 0) ### needs better permutation of NAs
      
pro_exp <- exprs(data_file)
exprs_vals <- pro_exp %>%
  replace(is.na(.),0)
is.na(ora_list_df)

# 1. Select columns for the Heatmap / matrix
heatmap_matrix <- ora_list_df %>% dplyr::select(Description,grp_id, p_log)

# 2. Convert Decription coloumns into Rownames
heatmap_matrix_1 <- heatmap_matrix [,-1]
rownames(heatmap_matrix_1) <- heatmap_matrix [,1]
heatmap_matrix_1 %>% replace(is.na(.),0) -> heatmap_matrix_1


# 3.Convert Column values into Columns
# Refer - https://mgimond.github.io/ES218/Week03b.html#separating_elements_in_one_column_into_separate_columns
# matrix_3 <- heatmap_matrix_1 %>% spread(p_log, grp_id)
matrix_3 <- pivot_wider(heatmap_matrix, 
                        #id_cols = NULL,
                        names_from = "grp_id", 
                        values_from = "p_log",
                        values_fn = list("p_log" = min)) 

# Replace 0 values
matrix_3 <- matrix_3 %>% replace(is.na(.),0)
is.na(matrix_3)

# Convert Decription coloumns into Rownames
# magrittr::set_rownames
#matrix_4 <- matrix_3 %>% `rownames<-` (c("Description")) 

matrix_3_1 <- tibble::column_to_rownames(matrix_3, var = "Description") 

# Use the filtered experiment result on proteins vs. samples for plotting
out <- pheatmap::pheatmap(matrix_3_1, 
                          scale = "row",
                          clustering_distance_rows = "euclidean",
                          clustering_distance_cols = "euclidean",
                          clustering_method = "complete", 
                          show_rownames = TRUE)
      
# the output will have info related to the number of clusters 
fdata(object) <- cutree(out$tree_row, k = k) %>% as.data.frame() %>%  `colnames<-`(c("clust_dclust")) %>% tibble::rownames_to_column(var = "feature_id") %>% dplyr::left_join(fdata(object), ., by = "feature_id")
      
    
        plot(out$tree_row)
        abline(h = out$tree_row$height[length(out$tree_row$height)-(k-2)], 
                 col = "red", lty = 2, lwd = 2)
     
      
  

```











```{r}
# df ordered by p_log - Dot plots and Bar plots
plot <- ora_list_df%>%
  arrange(grp_id, p_log) %>%
  mutate(order = row_number())

```
